### ISSUE TITLE
Auto start problem with site recommendation usage

### ISSUE THREAD

**Issue by asim215** [loh-tar/tbsm#10]
Hello. I used following code in my .zprofile.  
```
# Auto start tbsm after login on first two VTs
[[ $XDG_VTNR -le 2 ]] && tbsm
```
When I run tmux tbsm run in each terminal session. So I solve it with following:
```
if [[ ! ${DISPLAY} && ${XDG_VTNR} == 1 ]]; then
    exec tbsm
fi
```
Get from Gentoo forum and modified. Auto start only on tty1.

**Comment by loh-tar** [comment]
Well, these "recommendation" is slightly fuzzy formulated and for the advanced user only a hint of what todo. And you got it.

Interesting. Thanks for reporting, I will add a note to the doc for tmux user.

**Comment by asim215** [comment]
Also for fish shell in .config/fish/config.fish
```
if test "$DISPLAY" = "" -a "$XDG_VTNR" = 1
      tbsm
end
```
If $DISPLAY empty and XDG_VTR equals 1 then execute tbsm. Work with tmux. Test in sway, alacritty.
