### ISSUE TITLE
.Xresources and possibly .xinit support

### ISSUE THREAD

**Issue by antaxiom** [loh-tar/tbsm#14]
I like program a lot, but I find it can't replace what a login manager does for me. Since it doesn't seem to be loading the .Xresources file my dpi is totally off and my system is unusable (I use a hdpi display). I'm not quite sure what it would take to do this or why it couldn't be. I know development is inactive, so I don't expect much.

**Comment by loh-tar** [comment]
> I know development is inactive, so I don't expect much

That's good, thank you :) 

> I use a hdpi display

My laptop too. And I had some trouble at the time as it was new and had replaced my lovely old Netbook. But the trouble was before some tbsm or X was started.
So if your console font is too small and you can't hardly read your boot messages it's not related to tbsm or X. I hope that's it.

If your console font is fine and only X is too small just as you say, than I have no idea. It should it be changeable with your X tools, what ever you use.

**Comment by antaxiom** [comment]
My trouble had to do with X, ttys are fine. I set a scaling parameter in
.Xresources with my screen's dpi (Xft.dpi) and that makes programs scale as
needed.

**Comment by loh-tar** [comment]
After reading some of the [ArchWiki](https://wiki.archlinux.org/index.php/X_resources) I see what you mean by your first post regarding "support".

> Most Display managers load the ~/.Xresources file on login.

How about to do these `xrdb -merge` command just before you start _tbsm_? 
As a first test quit _tbsm_ after login, run these _xrdb_ stuff and run _tbsm_ again. When it works, add the _xrdb_ code to your _tbsm_ start code.

Edit: Remove unneeded stuff and hasty stupid conclusion

**Comment by HidingCherry** [comment]
> How about to do these `xrdb -merge` command just before you start _tbsm_?

I haven't used it yet - but after a little test I had to use `xrdb -merge -nocpp` instead.
Otherwise the preprocessor will interpret the comments.
