### ISSUE TITLE
Support for shell session?

### ISSUE THREAD

**Issue by bee-keeper** [loh-tar/tbsm#18]
Hi,

Thanks for this, I just set this up yesterday and it works nicely with the kind of aesthetic I was looking for.

Im wondering if there is a recommended approach for a shell option where instead of starting a desktop on X, I'm just dropped back into a shell session?  What I'm looking for is a choice between Xorg Gnome, Wayland Gnome or terminal without starting X at all.    

Thanks,

**Comment by loh-tar** [comment]
Um? I'm not sure what do you ask, sorry. Let me try to guess:
- tbsm is working as intended. After boot and login on some tty,  tbsm is showing up
- You can choose between sessions "Xorg Gnome" and  "Wayland Gnome" and and your are fine

Now you want an additionally  "shell session" ? What is that supposed to be? When you ask, "How to start some console program" then make it sense to me.

Yes you can. You need to create a .desktop file. I haven't try it on my own, but it may work when you copy that into the whitelist dir.

Here on my system I have only one program that offer such desktop file out of the box, micro editor.

```
[Desktop Entry]

Name=Micro
GenericName=Text Editor
Comment=Edit text files in a terminal

Icon=micro
Type=Application
Categories=Utility;TextEditor;Development;
Keywords=text;editor;syntax;terminal;

Exec=micro %F
StartupNotify=false
Terminal=true
```

The last line `Terminal=true` is the important one. The `Exec=micro %F` line is slightly tricky. It works here, but tbsm don't support to fill these `%F`.

You can search with `tbsm s "Terminal=true"` you installation if there is such kind of desktop file for some program. Hope that helps.

>...it works nicely with the kind of aesthetic I was looking for.

Thanks for the Thanks :-)

**Comment by loh-tar** [comment]
> The `Exec=micro %F` line is slightly tricky. It works here, but tbsm don't support to fill these `%F`.

Yeah. The problem with this is, that micro will take %F as the filename.

Perhaps you want this kind of session? 

```
~/.config/tbsm/whitelist/bash-session.desktop 

[Desktop Entry]
Name=Bash Session
Exec=bash -i
Terminal=true
```

You will dropped to a bash shell and with `exit` you came back to tbsm

**Comment by bee-keeper** [comment]
Yep that's the one.  Thank you
