### ISSUE TITLE
Handling tty after closing session i.e. logout

### ISSUE THREAD

**Issue by sandboiii** [loh-tar/tbsm#7]
I have successfully setup tbsm to start sessions from tty, but if close the session, the tty is no longer available to work with. It filled with messages and I can't type anything in it. Is there any way to handle this situation for example to show tbsm again or to be able to work with bash after that?

**Comment by loh-tar** [comment]
Damn, that's new! :-(
I have today updated my system (after ~month) and must sadly confirm this.

Prior it has worked. The screen was filled by some stuff but tbsm was coming back and every thing was good.

I have ATM no idea, any help is appreciated!

**Comment by loh-tar** [comment]
You are the one with Wayland at the Arch-Forum?
I'm on X only. So happens in both cases(?)

**Comment by loh-tar** [comment]
I seems it's systemd(240) related, there are some reports at the Arch-Forum, e.g. this one
https://bbs.archlinux.org/viewtopic.php?id=243298

So downgrade to 239 works here too, in my case this way
sudo pacman -U /var/cache/pacman/pkg/systemd-239.303-1-x86_64.pkg.tar.xz /var/cache/pacman/pkg/libsystemd-239.303-1-x86_64.pkg.tar.xz

Will keep that report open at least as long the problem exist.

**Comment by sandboiii** [comment]
@loh-tar yes it happens with both X and Wayland sessions. And downgrading systemd fixes both cases. Whats written in the systemd's changelog since this version?

**Comment by loh-tar** [comment]
Um, no idea!(?)

**Comment by sandboiii** [comment]
Probably the proper way to logout is to terminate the session as described [here](https://unix.stackexchange.com/questions/72203/logout-user-with-systemd). Currently I log out with commands ```i3-msg exit``` and ```swaymsg exit``` which just basically end the session. But mentioned method allows you to login in same tty you used to start terminated session and choose wm/de again

**Comment by sandboiii** [comment]
Since this issue is bound to systemd we can solve it by asking users to use method above to logout

**Comment by brunelli** [comment]
Seems to be fixed upstream: systemd/systemd#11269

Let's wait for confirmation after v241 is released or from someone testing this against systemd's master.

**Comment by loh-tar** [comment]
It's here working again. When you confirm this @Sandmonster pls close it.
systemd 241.7-2

**Comment by sandboiii** [comment]
Yeah, it's working, everything is good now, thank you!
